pretzel:
  engine: liquid
exclude:
- publish.ps1
- build.cake
- build.ps1
- tools\
- .vscode\
- .git\
- .git
- .gitignore
- add-post.cmd
- add-tag.cmd
- add-draft.cmd
- add-series.cmd
- taste.cmd
- taste-drafts.cmd
- git-clean.cmd
- build.bat
- cake.config
- tests\
- js\
- css\
- img\
- node_modules\
- _data\
include:
- downloads
- .htaccess
author: Manuel Grundner
author-email: m.grundner@delegate.at
author-github: biohazard999
site-title: blog.delegate.at
site-name: blog.delegate.at
feed-name: blog.delegate.at
site-url: https://blog.delegate.at
site-repo: https://www.github.com/xenial-io/Xenial.Blog
version: 0.0.0-alpha.0.456
commit: 72c6eb37212b3ec0d7c7a5d73b80e566e9ae8efc
last-update: 2024-10-11
comment-repo: https://github.com/xenial-io/Xenial.Blog.Comments.git
comment-url: https://github.com/xenial-io/Xenial.Blog.Comments
comment-branch: main
comment-api: https://comments.xenial.io
